### ISSUE TITLE
Does not reflect DST change for 2015

### ISSUE THREAD

**Issue by jmswisher** [djc/awmy#15]
The US and Canada changed to DST on March 8. This is not reflected in arewemeetingyet.com. For example, [this meeting link](http://arewemeetingyet.com/Los%20Angeles/2015-02-24/08:00/b/Dev%20Engage%20bi-weekly%20meeting) should show Pacific Time as UTC-7, but shows it as UTC-8.

**Comment by djc** [comment]
Sorry, I hope you detected this in time!

This seems to be the result of a change made for #13; fixing it without regressing the other one is a bit tricky, and will require some more thought than I can afford right now. Hope to fix soon.

**Comment by djc** [comment]
Should be fixed in d26a8dd.
