### ISSUE TITLE
Wrong date of next event

### ISSUE THREAD

**Issue by wagnerand** [djc/awmy#16]
...probably due to taking the wrong time into account when calculating, when the next even is going to be.

Example:
http://arewemeetingyet.com/Los%20Angeles/2015-03-10/12:00/b/Tb

So, for me being in Europe the next event should be *today*, however the page says:

Next occurrence, your time (UTC + 01:00):
Tue, 24th Mar, 20:00
(2 weeks from now)

**Comment by djc** [comment]
Yeah, sorry about this. This is the return of #13, which is temporary while I figure out a proper fix for #15 that doesn't regress this use case.

**Comment by djc** [comment]
Should be fixed with d26a8dd.
