### ISSUE TITLE
Feature Request: Meeting Conflict

### ISSUE THREAD

**Issue by bkerensa** [djc/awmy#19]
Would be nice of awmy could keep meetings stored and tell people if their proposed meeting time conflicts with other standing meetings. This would be very useful since we are a global org with so many teams.

**Comment by djc** [comment]
AWMY is not intended to be Mozilla-only, so I'm not sure it makes much sense. It's also currently very much stateless, so that this would not be an easy fix...

**Comment by djc** [comment]
As I consider this out of scope, closing.
