### ISSUE TITLE
ICS data missing correct TZ setup

### ISSUE THREAD

**Issue by neandr** [djc/awmy#20]
Just used the TB meeting ICS link
http://arewemeetingyet.com/Los%20Angeles/2015-04-07/12:00/b/Thunderbird%20Meeting

Afais the ICS data is incomplete to resolve it for other timezones (like mine living in Germany).
You have

```
    DTSTART;TZID=America/Los_Angeles:20150421T120000
```

But there is no VTIMEZONE block like this:

```
    BEGIN:VTIMEZONE
    TZID:Europe/Berlin
    X-LIC-LOCATION:Europe/Berlin
    BEGIN:DAYLIGHT
    TZOFFSETFROM:+0100
    TZOFFSETTO:+0200
    TZNAME:CEST
    DTSTART:19700329T020000
    RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
    END:DAYLIGHT
    BEGIN:STANDARD
    TZOFFSETFROM:+0200
    TZOFFSETTO:+0100
    TZNAME:CET
    DTSTART:19701025T030000
    RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
    END:STANDARD
    END:VTIMEZONE
```

For an international meeting it makes sense to have it complete?

**Comment by kewisch** [comment]
This should be fine given [rfc 7809](https://tools.ietf.org/rfcmarkup?doc=7809). Most clients support this. I'd suggest to close.

**Comment by djc** [comment]
Yay, thanks for bringing in your spec knowledge!
