### ISSUE TITLE
Create public app instance on Heroku

### ISSUE THREAD

**Issue by elimisteve** [djc/awmy#22]
This would be handy!

**Comment by elimisteve** [comment]
Running this on [Sandstorm Oasis](https://oasis.sandstorm.io/) would also be very convenient.

**Comment by djc** [comment]
Why? What's the problem just using the `arewemeetingyet.com` instance?

**Comment by elimisteve** [comment]
Ah I was viewing this on mobile and somehow missed the fact that http://arewemeetingyet.com/ exists. Thanks for running this service.
