### ISSUE TITLE
XSS issues with the meeting title

### ISSUE THREAD

**Issue by kewisch** [djc/awmy#24]
Using innerHTML is generally a bad idea unless you escape the data. Please check this URL:

http://arewemeetingyet.com/Berlin/2018-01-01/13:01/%3Cimg%20onerror%3D%22alert%28%27xss%27%29%22%20src%3D%22asdadsasdads%22%3E%3C%2Fimg%3E

Suggest to change everything to .textContent unless necessary and escape url content everywhere else.

**Comment by djc** [comment]
Thanks for the feedback! I've replaced all uses of `innerHTML`.
