### ISSUE TITLE
arewemeetingyet.com refused to connect

### ISSUE THREAD

**Issue by hugovk** [djc/awmy#28]
http://arewemeetingyet.com/ is currently down:

> ## This site can’t be reached
> arewemeetingyet.com refused to connect.
> Try:
> 
> Checking the connection
ERR_CONNECTION_REFUSED

**Comment by djc** [comment]
Sorry about that -- some breakage after a routine upgrade. Should be fine now!

**Comment by hugovk** [comment]
Looks good, thanks for the swift response and for the great website!
